# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-09 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dba_name', models.CharField(max_length=100)),
                ('aka_name', models.CharField(max_length=100)),
                ('license_number', models.IntegerField()),
                ('risk_level', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_id', models.IntegerField()),
                ('inspection_date', models.DateField()),
                ('inspection_type', models.CharField(max_length=50)),
                ('inspection_results', models.CharField(max_length=50)),
                ('violations', models.CharField(max_length=100)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_inspections.Establishment')),
            ],
        ),
    ]
